In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\RAZER\Downloads\score_updated.csv")

In [7]:
df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
..    ...     ...
91    5.8      60
92    4.4      44
93    6.1      63
94    3.7      37
95    8.0      84

[96 rows x 2 columns]

# Split

## Spliting in x and y

In [6]:
X = df["Hours"].values
y = df["Scores"].values

## Spliting In Training and Testing

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [16]:
X_train.shape

(76,)

In [17]:
X_test.shape

(20,)

# Teaining

In [19]:
from sklearn.linear_model import LinearRegression



#reshaping
X_train_reshaped = X_train.reshape(-1,1)
X_test_reshaped = X_test.reshape(-1,1)

#Model Declaration
lin_model = LinearRegression()

#Training
lin_model.fit(X_train_reshaped, y_train)

m_sk = lin_model.coef_[0]
c_sk = lin_model.intercept_

print(m_sk)
print(c_sk)

9.835635077805753
2.4405655921340568


# Evaluation

## Testing

In [28]:
y_prediction_test = lin_model.predict(X_test_reshaped)

In [29]:
y_prediction_test

array([28.01321679, 50.63517747, 31.94747083, 38.83241538, 82.10920972,
       87.02702726, 76.20782868, 68.33932061, 27.02965329, 78.17495569,
       55.55299501, 18.17758172, 62.43793957, 36.86528836, 90.96128129,
       95.87909883, 46.70092344, 39.81597889, 37.84885187, 51.61874098])

In [30]:
y_test

array([32, 51, 27, 37, 82, 89, 70, 71, 21, 85, 55, 19, 67, 30, 92, 90, 41,
       35, 36, 52])

## mean_absolute_error, mean_square_error, R2_score

In [34]:
from sklearn.metrics import  mean_absolute_error,mean_squared_error,r2_score

mae = mean_absolute_error(y_test, y_prediction_test)
mse = mean_squared_error(y_test, y_prediction_test)
r2 = r2_score(y_test, y_prediction_test)


print("Mean Absolute Error: ",mae)
print("Mean Squared Error: ",mse)
print("R^2 Score: ",r2)

Mean Absolute Error:  3.3702236454952397
Mean Squared Error:  17.007444250866516
R^2 Score:  0.9708871356050831


## Training

In [31]:
y_prediction_train = lin_model.predict(X_train_reshaped)

In [32]:
y_prediction_train

array([20.14470873, 96.86266234, 89.97771778, 69.32288412, 31.94747083,
       28.9967803 , 45.71735993, 60.47081255, 42.76666941, 47.68448695,
       25.06252627, 88.01059077, 44.73379643, 17.19401821, 74.24070166,
       58.50368554, 24.07896276, 27.02965329, 32.93103433, 40.7995424 ,
       56.53655852, 59.48724904, 59.48724904, 75.22426517, 57.52012203,
       43.75023292, 71.29001114, 34.89816135, 79.1585192 , 86.04346375,
       21.12827224, 54.5694315 , 84.07633674, 14.24332769, 92.92840831,
       35.88172486, 72.27357464, 41.7831059 , 85.05990025, 81.12564621,
       26.04608978, 38.83241538, 29.98034381, 83.09277323, 81.12564621,
       16.2104547 , 93.91197182, 62.43793957, 97.84622585, 94.89553532,
       53.585868  , 15.22689119, 61.45437606, 19.16114522, 63.42150307,
       98.82978935, 65.38863009, 23.09539926, 73.25713815, 64.40506658,
       48.66805046, 52.60230449, 67.35575711, 49.65161397, 33.91459784,
       70.30644763, 22.11183575, 30.96390732, 69.32288412, 12.27

In [33]:
y_train

array([21, 98, 95, 74, 34, 25, 45, 62, 44, 48, 23, 87, 43, 20, 77, 59, 22,
       30, 28, 38, 60, 60, 63, 69, 57, 49, 73, 42, 86, 75, 24, 56, 81, 14,
       88, 33, 73, 40, 84, 84, 26, 37, 29, 83, 79, 15, 94, 63, 96, 93, 53,
       16, 61, 18, 68, 99, 64, 20, 72, 66, 50, 47, 72, 54, 27, 76, 18, 31,
       67, 12, 30, 78, 65, 17, 44, 80])

## mean_absolute_error,mean_squared_error,r2_score

In [35]:
from sklearn.metrics import  mean_absolute_error,mean_squared_error,r2_score

mae = mean_absolute_error(y_train, y_prediction_train)
mse = mean_squared_error(y_train, y_prediction_train)
r2 = r2_score(y_train, y_prediction_train)


print("Mean Absolute Error: ",mae)
print("Mean Squared Error: ",mse)
print("R^2 Score: ",r2)

Mean Absolute Error:  2.4084933698218722
Mean Squared Error:  10.202649265960442
R^2 Score:  0.9837693861888686


# For single value predictions

In [41]:
data = float(input())

single_prediction = lin_model.predict([[data]])

print("The predicted Score:",single_prediction)

The predicted Score: [31.94747083]


# Saving the Model

In [44]:
import joblib

joblib.dump(lin_model, "LR_study_hours_score_RJ.pkl")

['LR_study_hours_score_RJ.pkl']