In [1]:
print ("Hi! Welcome")

Hi! Welcome


In [3]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/RafsanJany-44/Machine-School/refs/heads/main/datasets/EEG_HMC.csv")

In [4]:
df

Sleep_Stage  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0                W         0.00051           8.74146        18.48195   
1                W         0.00040          10.24000        17.48293   
2                W         0.00036           9.74049        17.98244   
3                W         0.00035          10.11512        17.60780   
4                W         0.00033           9.74049        17.60780   
...            ...             ...               ...             ...   
108446          N1         0.00031          10.11512        17.48293   
108447          N1         0.00042           9.99024        16.35902   
108448          N1         0.00040           9.86537        15.73463   
108449           W         0.00051          10.11512        17.85756   
108450           W         0.00128          10.61463        21.47902   

        Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  \
0                     17.48293         8.24195        0.00071   
1                     16.85854        10.61463        0.00051   
2                     17.48293         8.74146        0.00047   
3                     17.10829         9.61561        0.00047   
4                     17.23317         8.11707        0.00043   
...                        ...             ...            ...   
108446                16.85854        10.11512        0.00039   
108447                15.85951         9.86537        0.00044   
108448                14.98537        10.36488        0.00037   
108449                17.48293        11.61366        0.00075   
108450                21.35415         8.24195        0.00304   

        MedianF_Beta_F4  MeanF_Beta_F4  Spectral Edge_Beta_F4  ...  \
0              19.73073       29.84585               33.84195  ...   
1              17.23317       26.34927               29.34634  ...   
2              17.60780       25.47512               28.22244  ...   
3              17.35805       26.47415               28.72195  ...   
4              17.23317       25.84976               28.09756  ...   
...                 ...            ...                    ...  ...   
108446         16.73366       24.97561               26.97366  ...   
108447         15.73463       24.85073               26.47415  ...   
108448         14.48585       22.72780               24.10146  ...   
108449         19.73073       29.72098               32.96780  ...   
108450         23.22732       33.21756               38.08780  ...   

        MeanP_Delta_O2  MedianF_Delta_O2  MeanF_Delta_O2  \
0              0.00724           0.74927         3.87122   
1              0.00723           0.49951         3.74634   
2              0.00230           0.62439         5.24488   
3              0.00091           0.87415         6.61854   
4              0.00175           0.49951         5.74439   
...                ...               ...             ...   
108446         0.00101           1.12390         6.99317   
108447         0.00426           1.12390         5.24488   
108448         0.00116           0.87415         7.36780   
108449         0.00508           0.87415         5.36976   
108450         0.02494           0.87415         4.49561   

        Spectral Edge_Delta_O2  PeakF_Delta_O2  MeanP_Gamma_O2  \
0                      1.99805         0.87415        0.000210   
1                      1.24878         0.49951        0.000095   
2                      2.12293         0.62439        0.000074   
3                      3.12195         0.62439        0.000082   
4                      2.24780         0.49951        0.000077   
...                        ...             ...             ...   
108446                 3.74634         0.49951        0.000063   
108447                 2.24780         1.24878        0.000065   
108448                 3.99610         0.74927        0.000041   
108449                 1.99805         0.99902        0.000240   
108450                 2.12293         0.49951        0.001630   

      

In [5]:
df.columns

Index(['Sleep_Stage', 'MeanP_Alpha_F4', 'MedianF_Alpha_F4', 'MeanF_Alpha_F4',
       'Spectral Edge_Alpha_F4', 'PeakF_Alpha_F4', 'MeanP_Beta_F4',
       'MedianF_Beta_F4', 'MeanF_Beta_F4', 'Spectral Edge_Beta_F4',
       'PeakF_Beta_F4', 'MeanP_Theta_F4', 'MedianF_Theta_F4', 'MeanF_Theta_F4',
       'Spectral Edge_Theta_F4', 'PeakF_Theta_F4', 'MeanP_Delta_F4',
       'MedianF_Delta_F4', 'MeanF_Delta_F4', 'Spectral Edge_Delta_F4',
       'PeakF_Delta_F4', 'MeanP_Gamma_F4', 'MedianF_Gamma_F4',
       'MeanF_Gamma_F4', 'Spectral Edge_Gamma_F4', 'PeakF_Gamma_F4',
       'MeanP_Alpha_C4', 'MedianF_Alpha_C4', 'MeanF_Alpha_C4',
       'Spectral Edge_Alpha_C4', 'PeakF_Alpha_C4', 'MeanP_Beta_C4',
       'MedianF_Beta_C4', 'MeanF_Beta_C4', 'Spectral Edge_Beta_C4',
       'PeakF_Beta_C4', 'MeanP_Theta_C4', 'MedianF_Theta_C4', 'MeanF_Theta_C4',
       'Spectral Edge_Theta_C4', 'PeakF_Theta_C4', 'MeanP_Delta_C4',
       'MedianF_Delta_C4', 'MeanF_Delta_C4', 'Spectral Edge_Delta_C4',
       'PeakF_D

In [8]:
list(df.columns)

['Sleep_Stage',
 'MeanP_Alpha_F4',
 'MedianF_Alpha_F4',
 'MeanF_Alpha_F4',
 'Spectral Edge_Alpha_F4',
 'PeakF_Alpha_F4',
 'MeanP_Beta_F4',
 'MedianF_Beta_F4',
 'MeanF_Beta_F4',
 'Spectral Edge_Beta_F4',
 'PeakF_Beta_F4',
 'MeanP_Theta_F4',
 'MedianF_Theta_F4',
 'MeanF_Theta_F4',
 'Spectral Edge_Theta_F4',
 'PeakF_Theta_F4',
 'MeanP_Delta_F4',
 'MedianF_Delta_F4',
 'MeanF_Delta_F4',
 'Spectral Edge_Delta_F4',
 'PeakF_Delta_F4',
 'MeanP_Gamma_F4',
 'MedianF_Gamma_F4',
 'MeanF_Gamma_F4',
 'Spectral Edge_Gamma_F4',
 'PeakF_Gamma_F4',
 'MeanP_Alpha_C4',
 'MedianF_Alpha_C4',
 'MeanF_Alpha_C4',
 'Spectral Edge_Alpha_C4',
 'PeakF_Alpha_C4',
 'MeanP_Beta_C4',
 'MedianF_Beta_C4',
 'MeanF_Beta_C4',
 'Spectral Edge_Beta_C4',
 'PeakF_Beta_C4',
 'MeanP_Theta_C4',
 'MedianF_Theta_C4',
 'MeanF_Theta_C4',
 'Spectral Edge_Theta_C4',
 'PeakF_Theta_C4',
 'MeanP_Delta_C4',
 'MedianF_Delta_C4',
 'MeanF_Delta_C4',
 'Spectral Edge_Delta_C4',
 'PeakF_Delta_C4',
 'MeanP_Gamma_C4',
 'MedianF_Gamma_C4',
 'MeanF_G

In [9]:
col_list = list(df.columns)

## Separating column which will be X and Y

In [13]:
col_list[0]

'Sleep_Stage'

In [12]:
col_list[1:]

['MeanP_Alpha_F4',
 'MedianF_Alpha_F4',
 'MeanF_Alpha_F4',
 'Spectral Edge_Alpha_F4',
 'PeakF_Alpha_F4',
 'MeanP_Beta_F4',
 'MedianF_Beta_F4',
 'MeanF_Beta_F4',
 'Spectral Edge_Beta_F4',
 'PeakF_Beta_F4',
 'MeanP_Theta_F4',
 'MedianF_Theta_F4',
 'MeanF_Theta_F4',
 'Spectral Edge_Theta_F4',
 'PeakF_Theta_F4',
 'MeanP_Delta_F4',
 'MedianF_Delta_F4',
 'MeanF_Delta_F4',
 'Spectral Edge_Delta_F4',
 'PeakF_Delta_F4',
 'MeanP_Gamma_F4',
 'MedianF_Gamma_F4',
 'MeanF_Gamma_F4',
 'Spectral Edge_Gamma_F4',
 'PeakF_Gamma_F4',
 'MeanP_Alpha_C4',
 'MedianF_Alpha_C4',
 'MeanF_Alpha_C4',
 'Spectral Edge_Alpha_C4',
 'PeakF_Alpha_C4',
 'MeanP_Beta_C4',
 'MedianF_Beta_C4',
 'MeanF_Beta_C4',
 'Spectral Edge_Beta_C4',
 'PeakF_Beta_C4',
 'MeanP_Theta_C4',
 'MedianF_Theta_C4',
 'MeanF_Theta_C4',
 'Spectral Edge_Theta_C4',
 'PeakF_Theta_C4',
 'MeanP_Delta_C4',
 'MedianF_Delta_C4',
 'MeanF_Delta_C4',
 'Spectral Edge_Delta_C4',
 'PeakF_Delta_C4',
 'MeanP_Gamma_C4',
 'MedianF_Gamma_C4',
 'MeanF_Gamma_C4',
 'Spec

In [6]:
df.shape

(108451, 76)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108451 entries, 0 to 108450
Data columns (total 76 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Sleep_Stage             108451 non-null  object 
 1   MeanP_Alpha_F4          108451 non-null  float64
 2   MedianF_Alpha_F4        108451 non-null  float64
 3   MeanF_Alpha_F4          108451 non-null  float64
 4   Spectral Edge_Alpha_F4  108451 non-null  float64
 5   PeakF_Alpha_F4          108451 non-null  float64
 6   MeanP_Beta_F4           108451 non-null  float64
 7   MedianF_Beta_F4         108451 non-null  float64
 8   MeanF_Beta_F4           108451 non-null  float64
 9   Spectral Edge_Beta_F4   108451 non-null  float64
 10  PeakF_Beta_F4           108451 non-null  float64
 11  MeanP_Theta_F4          108451 non-null  float64
 12  MedianF_Theta_F4        108451 non-null  float64
 13  MeanF_Theta_F4          108451 non-null  float64
 14  Spectral Edge_Theta_

## Student Study Hours Data

In [17]:
import pandas as pd

df = pd.read_csv(r"c:\Users\user\Downloads\Python\score_updated.csv")

df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
..    ...     ...
91    5.8      60
92    4.4      44
93    6.1      63
94    3.7      37
95    8.0      84

[96 rows x 2 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   96 non-null     float64
 1   Scores  96 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 1.6 KB


## Predicting the Study Score from Study Hours

## Splitting X and Y variables

In [22]:
x = df["Hours"].values
y = df["Scores"].values

## Splitting Training and Testing Dataset

In [45]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

In [40]:
x_train.shape

(76,)

In [41]:
x_test.shape

(20,)

## Reshaping (only x)

In [58]:
x_train

array([1.8, 9.6, 8.9, 6.8, 3. , 2.7, 4.4, 5.9, 4.1, 4.6, 2.3, 8.7, 4.3,
       1.5, 7.3, 5.7, 2.2, 2.5, 3.1, 3.9, 5.5, 5.8, 5.8, 7.4, 5.6, 4.2,
       7. , 3.3, 7.8, 8.5, 1.9, 5.3, 8.3, 1.2, 9.2, 3.4, 7.1, 4. , 8.4,
       8. , 2.4, 3.7, 2.8, 8.2, 8. , 1.4, 9.3, 6.1, 9.7, 9.4, 5.2, 1.3,
       6. , 1.7, 6.2, 9.8, 6.4, 2.1, 7.2, 6.3, 4.7, 5.1, 6.6, 4.8, 3.2,
       6.9, 2. , 2.9, 6.8, 1. , 2.7, 7.6, 6.5, 1.1, 4.4, 7.9])

In [57]:
x_train_reshaped = x_train.reshape(-1,1)

x_train_reshaped

array([[1.8],
       [9.6],
       [8.9],
       [6.8],
       [3. ],
       [2.7],
       [4.4],
       [5.9],
       [4.1],
       [4.6],
       [2.3],
       [8.7],
       [4.3],
       [1.5],
       [7.3],
       [5.7],
       [2.2],
       [2.5],
       [3.1],
       [3.9],
       [5.5],
       [5.8],
       [5.8],
       [7.4],
       [5.6],
       [4.2],
       [7. ],
       [3.3],
       [7.8],
       [8.5],
       [1.9],
       [5.3],
       [8.3],
       [1.2],
       [9.2],
       [3.4],
       [7.1],
       [4. ],
       [8.4],
       [8. ],
       [2.4],
       [3.7],
       [2.8],
       [8.2],
       [8. ],
       [1.4],
       [9.3],
       [6.1],
       [9.7],
       [9.4],
       [5.2],
       [1.3],
       [6. ],
       [1.7],
       [6.2],
       [9.8],
       [6.4],
       [2.1],
       [7.2],
       [6.3],
       [4.7],
       [5.1],
       [6.6],
       [4.8],
       [3.2],
       [6.9],
       [2. ],
       [2.9],
       [6.8],
       [1. ],
       [2.7],
      

## Import the Linear Regression Function

In [25]:
from sklearn.linear_model import LinearRegression

## Generate the Function for Finding the m and c value

### Training dataset 

In [47]:
x = df["Hours"].values
y = df["Scores"].values

#reshaping
x_train_reshaped = x_train.reshape(-1,1)
x_test_reshaped = x_test.reshape(-1,1)

#Model Declaration
lin_model = LinearRegression()

#Training
lin_model.fit(x_train_reshaped, y_train)

m_sk = lin_model.coef_[0]
c_sk = lin_model.intercept_

print(m_sk)
print(c_sk)

9.835635077805753
2.4405655921340568


 ## <font color = red heart> Predicting the Y value from X value (MANUAL WAY) </font>

In [32]:
hours = float(input())

scores = hours * m_sk + c_sk

print(scores)

62.26161800951831


 ## <font color = red heart> Predicting the Y value from X value (USING SKLEARN LIBRARY) </font>

### <b> Evaluation from Training Dataset </b>

In [60]:
y_prediction_train = lin_model.predict(x_train_reshaped)

In [61]:
y_prediction_train

array([20.14470873, 96.86266234, 89.97771778, 69.32288412, 31.94747083,
       28.9967803 , 45.71735993, 60.47081255, 42.76666941, 47.68448695,
       25.06252627, 88.01059077, 44.73379643, 17.19401821, 74.24070166,
       58.50368554, 24.07896276, 27.02965329, 32.93103433, 40.7995424 ,
       56.53655852, 59.48724904, 59.48724904, 75.22426517, 57.52012203,
       43.75023292, 71.29001114, 34.89816135, 79.1585192 , 86.04346375,
       21.12827224, 54.5694315 , 84.07633674, 14.24332769, 92.92840831,
       35.88172486, 72.27357464, 41.7831059 , 85.05990025, 81.12564621,
       26.04608978, 38.83241538, 29.98034381, 83.09277323, 81.12564621,
       16.2104547 , 93.91197182, 62.43793957, 97.84622585, 94.89553532,
       53.585868  , 15.22689119, 61.45437606, 19.16114522, 63.42150307,
       98.82978935, 65.38863009, 23.09539926, 73.25713815, 64.40506658,
       48.66805046, 52.60230449, 67.35575711, 49.65161397, 33.91459784,
       70.30644763, 22.11183575, 30.96390732, 69.32288412, 12.27

In [ ]:
y_train

array([21, 98, 95, 74, 34, 25, 45, 62, 44, 48, 23, 87, 43, 20, 77, 59, 22,
       30, 28, 38, 60, 60, 63, 69, 57, 49, 73, 42, 86, 75, 24, 56, 81, 14,
       88, 33, 73, 40, 84, 84, 26, 37, 29, 83, 79, 15, 94, 63, 96, 93, 53,
       16, 61, 18, 68, 99, 64, 20, 72, 66, 50, 47, 72, 54, 27, 76, 18, 31,
       67, 12, 30, 78, 65, 17, 44, 80])

### <b> Evaluation from Testing Dataset </b>

In [64]:
y_prediction_test = lin_model.predict(x_test_reshaped)

In [65]:
y_prediction_test

array([28.01321679, 50.63517747, 31.94747083, 38.83241538, 82.10920972,
       87.02702726, 76.20782868, 68.33932061, 27.02965329, 78.17495569,
       55.55299501, 18.17758172, 62.43793957, 36.86528836, 90.96128129,
       95.87909883, 46.70092344, 39.81597889, 37.84885187, 51.61874098])

In [66]:
y_test

array([32, 51, 27, 37, 82, 89, 70, 71, 21, 85, 55, 19, 67, 30, 92, 90, 41,
       35, 36, 52])

## <font color = yellow> <b> Mean_Absolute_Error, Mean_Squared_Error, R2 Score </b> </font>

### in Linear Regression --> R2 score is the accuracy score

<font color = yellow> From the Testing dataset --> higher MAE and lower R2 </font>

In [67]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_prediction_test)
mse = mean_squared_error(y_test, y_prediction_test)
r2 = r2_score(y_test, y_prediction_test)

print("Mean Absolute Error:", mae)
print("Mean Squared Error", mse)
print("R2 Score:", r2)


Mean Absolute Error: 3.3702236454952397
Mean Squared Error 17.007444250866516
R2 Score: 0.9708871356050831


<font color = yellow> From the Testing dataset --> lower MAE and higher R2 </font>

In [68]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_train, y_prediction_train)
mse = mean_squared_error(y_train, y_prediction_train)
r2 = r2_score(y_train, y_prediction_train)

print("Mean Absolute Error:", mae)
print("Mean Squared Error", mse)
print("R2 Score:", r2)

Mean Absolute Error: 2.4084933698218722
Mean Squared Error 10.202649265960442
R2 Score: 0.9837693861888686


## <font color = orange> <b> Predicting single value </font> </b>

using two brackets in data because in the reshaped dataset

In [70]:
data = float(input())

single_prediction = lin_model.predict([[data]])

print("The Predicted Score:", single_prediction)



The Predicted Score: [31.94747083]


## <font color = pink> <b> Saving the Model </b> </font>

In [76]:
import joblib
joblib.dump(lin_model, "LR_study_hours_score_SHA.pkl")

['LR_study_hours_score_SHA.pkl']